version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pablo123
      MYSQL_DATABASE: typescript
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql